### PR TITLE
Handle git-style diff file paths.

### PR DESCRIPTION
**Pull request by bwinton**
It always bothered me that I couldn't open up files from git diffs.

(I am by no means a coffeescript guru, so if there's an easier or cleaner way to do any of this, please let me know! :smile:)

### CODE REVIEW

**Comment by t9md** [comment]
When I opened `foo.diff` file created by `git diff > foo.diff`, grammar is still not `source.diff`.
Are you installing specific language package like https://atom.io/packages/language-diff?

**Comment by bwinton** [comment]
Dang.  So I was.  Should I check the file extension instead?
(I also fixed the failing tests.)

**Comment by t9md** [comment]
Although I didn't check behavior yet, seems good overall.

But I don't think we need to check grammar scope and extension check.
Just push list of file to be checked with lowest priority(tail of list) , if no other file found then try to find file which file path have filename `a/`, `b/` portion removed.

**Comment by bwinton** [comment]
Did you mean something like this?

**Comment by t9md** [comment]
Yes, I like this style until things getting mess, currently logic is very simple and I like this.

Since I have to go to bed now, will check tomorrow. Thanks!

**Comment by t9md** [comment]
released as v0.1.8, I implemented it by myself( I didn't want to change getFilePath to take dirName arg).
Thanks for your suggestion.

**Comment by bwinton** [comment]
Awesome, thanks!  (I'm way more interested in the feature than in my implementation of it. :grinning:)

**Pull request closed without merging**
